In [1]:
import numpy as np

### Creating Arrays

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [14]:
a = np.array([1, 2, 3, 5, 7, 12])
print(a[2])
a[2] = 10
print(a[2])

3
10


In [21]:
print(np.arange(3, 10))
print([x for x in range(3, 10)])

[3 4 5 6 7 8 9]
[3, 4, 5, 6, 7, 8, 9]


In [26]:
np.linspace(0, 100, 15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [28]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [35]:
n[1, 2] = 20

print(n)

[[ 1  2  3]
 [ 4  5 20]
 [ 7  8  9]]


In [49]:
a = np.array([2, 4, 5, 6])
b = np.array([1, 0, 0, 2])

a.dot(b)

14

In [56]:
def matrix_vector_multiplication(U: np.ndarray, v: np.ndarray):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    return [x.dot(v) for x in U]

In [58]:
a = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
b = np.array([1, 0, 0, 2])

matrix_vector_multiplication(a, b)
a.dot(b)

array([14,  5,  5])

In [64]:
I = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

I_NP = np.eye(4)

print(I)
print(I_NP)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [65]:
a.dot(I_NP)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])